# Generated by Django 4.0 on 2021-12-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProName', models.CharField(max_length=50)),
                ('ProPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProDescription', models.TextField()),
                ('ProCost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProCreated', models.DateTimeField()),
            ],
        ),
    ]
