# Generated by Django 4.0 on 2021-12-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProCost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProCreated',
            field=models.DateTimeField(verbose_name='product at'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProDescription',
            field=models.TextField(verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProName',
            field=models.CharField(max_length=50, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProPrice',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='product price'),
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductImage', models.ImageField(upload_to='product/%y/%m/%d', verbose_name='Image')),
                ('ProIProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product')),
            ],
        ),
    ]
