# Generated by Django 4.0 on 2021-12-28 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_proimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProCost',
        ),
    ]
