# Generated by Django 4.0 on 2021-12-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_procost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProColor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='product Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='product Size'),
        ),
    ]
