# Generated by Django 4.0 on 2021-12-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_procolor_product_prosize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='ProSlug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
