# Generated by Django 4.0 on 2021-12-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_options_product_proslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ProSlug',
            new_name='slug',
        ),
    ]
