# Generated by Django 4.0 on 2021-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_rename_proslug_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='slug',
            new_name='ProSlug',
        ),
    ]
