# Generated by Django 4.0 on 2022-01-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_category_slug_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
