# Generated by Django 4.0 on 2022-01-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProSlug',
        ),
    ]
