# Generated by Django 4.0 on 2021-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BrandName', models.CharField(max_length=40)),
                ('BrandDescription', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Varint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VarintName', models.CharField(max_length=40)),
                ('VarintDescription', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Varint',
                'verbose_name_plural': 'Varints',
            },
        ),
    ]
